### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-server-modules/parse-server-gcloud-pubsub#10]

**Comment by ranhsd** [comment]
Hi @jcguarinpenaranda 

In your config.json file add the following inside the liveQuery block:

```
  "liveQuery": {
        "pubSubAdapter": "parse-server-gcloud-pubsub",
        "classNames": [
            "MyClass1",
            "MyClass2",
           ...
        ]
    },
```

If you run your parse-server on google cloud platform that's the only thing that you need to do. Otherwise you will need also to set 2 env variables: 

1. **process.env.GOOGLE_APPLICATION_CREDENTIALS** - this is your google cloud credentials 
2. **process.env.GCLOUD_PROJECT** - this env variable should point to your project id in google cloud platform where you run the pub sub service

You can read more about it in here: 

https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.8.0/guides/authentication

**Comment by jcguarinpenaranda** [comment]
Thank you

2017-11-07 11:24 GMT-05:00 Ran Hassid <notifications@github.com>:
